name: Compare OpenAPI Spec Changes
on:
  pull_request:
    paths:
      - 'openapi-spec.json'
      - 'openapi-spec.yaml'
jobs:
  compare_openapi_specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # This fetches the complete history
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install deepdiff
      
      - name: Compare OpenAPI Specs
        run: |
          # Get the base commit of the pull request
          BASE_COMMIT=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          
          # Copy current spec to a temporary location
          cp openapi-spec.json current_spec.json || cp openapi-spec.yaml current_spec.yaml
          
          # Checkout the base commit version of the spec
          git checkout $BASE_COMMIT -- openapi-spec.json openapi-spec.yaml
          
          # Rename the base version
          if [ -f openapi-spec.json ]; then
            mv openapi-spec.json base_spec.json
          elif [ -f openapi-spec.yaml ]; then
            mv openapi-spec.yaml base_spec.yaml
          fi
          
          # Restore the current version
          if [ -f current_spec.json ]; then
            mv current_spec.json openapi-spec.json
          elif [ -f current_spec.yaml ]; then
            mv current_spec.yaml openapi-spec.yaml
          fi
          
          # Run the comparison
          python3 compare_openapi_specs.py
