name: OpenAPI Impact Analysis

on:
  pull_request:
    paths:
      - 'openapi-spec.yaml'

jobs:
  analyze-impact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # required for accessing previous commit

      - name: Checkout api-dependencies repository
        uses: actions/checkout@v2
        with:
          repository: taimuraq/api-dependencies-repo
          path: api-dependencies

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install openai pyyaml deepdiff

      - name: Pull oasdiff Docker image
        run: docker pull tufin/oasdiff:latest
      
      - name: Create wrapper script for oasdiff
        run: |
          echo '#!/bin/bash
          docker run --rm -v $(pwd):/specs tufin/oasdiff:latest "$@"' > /usr/local/bin/oasdiff
          chmod +x /usr/local/bin/oasdiff
          
      - name: Verify oasdiff installation
        run: oasdiff --version

      - name: Copy dependencies.json for analysis
        run: |
          cp api-dependencies/shopper-api-dependencies.json ./shopper-api-dependencies.json

      - name: Compare OpenAPI Specs
        run: |
          BASE_COMMIT=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          cp openapi-spec.yaml new_spec.yaml
          git checkout $BASE_COMMIT -- openapi-spec.yaml
          mv openapi-spec.yaml old_spec.yaml

      - name: Running OpenAPI Spec diff action
        uses: oasdiff/oasdiff-action/changelog@main
        with:
            base: 'old_spec.yaml'
            revision: 'new_spec.yaml'

      - name: Setup GitHub CLI
        uses: cli/cli/action@v1

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Run OpenAPI impact analysis and LLM feedback
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Make sure this secret is set
        run: |
          python impact_analysis.py old_spec.yaml new_spec.yaml shopper-api-dependencies.json

      - name: Post LLM impact as PR comment
        run: |
          jq -Rs --slurpfile content llm_analysis.txt '{"body": $content[0]}' > payload.json
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
               -X POST \
               --data @payload.json \
               https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
