name: OpenAPI Impact Analysis

on:
  pull_request:
    paths:
      - 'openapi-spec.yaml'

jobs:
  analyze-impact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # required for accessing previous commit

      - name: Checkout api-dependencies repository
        uses: actions/checkout@v2
        with:
          repository: taimuraq/api-dependencies-repo
          path: api-dependencies

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install openai pyyaml deepdiff

      - name: Install oasdiff using Go
        run: |
          # Install Go if not already installed
          command -v go >/dev/null 2>&1 || { 
          echo "Installing Go..." 
          sudo apt-get update && sudo apt-get install -y golang
          }
    
          # Install oasdiff
          go install github.com/Tufin/oasdiff/cmd/oasdiff@latest
    
          # Make sure it's in PATH
          echo "${HOME}/go/bin" >> $GITHUB_PATH
    
          # Verify installation
          ${HOME}/go/bin/oasdiff version

      - name: Copy dependencies.json for analysis
        run: |
          cp api-dependencies/shopper-api-dependencies.json ./shopper-api-dependencies.json

      - name: Compare OpenAPI Specs
        run: |
          BASE_COMMIT=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          cp openapi-spec.yaml new_spec.yaml
          git checkout $BASE_COMMIT -- openapi-spec.yaml
          mv openapi-spec.yaml old_spec.yaml

      - name: Run OpenAPI impact analysis and LLM feedback
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Make sure this secret is set
        run: |
          python impact_analysis.py old_spec.yaml new_spec.yaml shopper-api-dependencies.json
