name: OpenAPI Impact Analysis

on:
  pull_request:
    paths:
      - 'openapi-spec.yaml'

permissions:
  pull-requests: write
  contents: read

jobs:
  analyze-impact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # required for accessing previous commit

      - name: Checkout api-dependencies repository
        uses: actions/checkout@v2
        with:
          repository: taimuraq/api-dependencies-repo
          path: api-dependencies

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install openai pyyaml deepdiff

      - name: Install oasdiff directly
        run: |
          # First, let's check what the latest release is
          echo "Checking latest release info"
          RELEASE_INFO=$(curl -s https://api.github.com/repos/Tufin/oasdiff/releases/latest)
          echo "Release info retrieved"
          
          # Print out the browser_download_url lines to see what's available
          echo "Available downloads:"
          echo "$RELEASE_INFO" | grep "browser_download_url"
          
          # Try to extract just the Linux AMD64 download URL
          DOWNLOAD_URL=$(echo "$RELEASE_INFO" | grep "browser_download_url.*linux_amd64.tar.gz" | cut -d '"' -f 4)
          echo "Download URL: $DOWNLOAD_URL"
          
          # If we found a URL, download it
          if [ -n "$DOWNLOAD_URL" ]; then
            echo "Downloading from $DOWNLOAD_URL"
            wget "$DOWNLOAD_URL" -O oasdiff_linux_amd64.tar.gz
            
            # Extract and install if download was successful
            if [ -f oasdiff_linux_amd64.tar.gz ]; then
              echo "Extracting archive"
              tar -xzf oasdiff_linux_amd64.tar.gz
              
              echo "Installing to /usr/local/bin"
              sudo mv oasdiff /usr/local/bin/
              sudo chmod +x /usr/local/bin/oasdiff
              
              echo "Verifying installation"
              oasdiff version
            else
              echo "Download failed"
            fi
          else
            echo "Could not find download URL for linux_amd64.tar.gz"
            
            # Fallback to a known version as a last resort
            echo "Trying fallback to specific version v1.11.3"
            wget "https://github.com/Tufin/oasdiff/releases/download/v1.11.3/oasdiff_Linux_x86_64.tar.gz" -O oasdiff_linux_amd64.tar.gz
            
            if [ -f oasdiff_linux_amd64.tar.gz ]; then
              echo "Extracting archive"
              tar -xzf oasdiff_linux_amd64.tar.gz
              
              echo "Installing to /usr/local/bin"
              sudo mv oasdiff /usr/local/bin/
              sudo chmod +x /usr/local/bin/oasdiff
              
              echo "Verifying installation"
              oasdiff version
            else
              echo "Fallback download also failed"
            fi
          fi

      - name: Copy dependencies.json for analysis
        run: |
          cp api-dependencies/shopper-api-dependencies.json ./shopper-api-dependencies.json

      - name: Compare OpenAPI Specs
        run: |
          BASE_COMMIT=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          cp openapi-spec.yaml new_spec.yaml
          git checkout $BASE_COMMIT -- openapi-spec.yaml
          mv openapi-spec.yaml old_spec.yaml

      - name: Running OpenAPI Spec diff action
        uses: oasdiff/oasdiff-action/changelog@main
        with:
            base: 'old_spec.yaml'
            revision: 'new_spec.yaml'

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
    
      - name: Verify GitHub CLI installation
        run: gh --version

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Run OpenAPI impact analysis and LLM feedback
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Make sure this secret is set
        run: |
          python impact_analysis.py old_spec.yaml new_spec.yaml shopper-api-dependencies.json

      - name: Get PR number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Comment on PR with LLM Analysis
        run: |
          gh pr comment "$PR_NUMBER" --body "$(<llm_analysis.txt)"
